### ISSUE TITLE
Get customer request not working in v0.7

### ISSUE THREAD

**Issue by javoeria** [googleads/google-ads-ruby#26]
After the v0.7 update, the method "get_customer" of customer service is not working and it gets an error:

`undefined method 'customer_id' for #<Google::Ads::GoogleAds::V0::Services::GetCustomerRequest>`

You can check it in the "get_account_information.rb" example. Thanks.

**Comment by mcloonan** [comment]
Thanks for the report; I'm also able to reproduce. I'm looking into it now.
